### PR TITLE
Add blis license

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes https://github.com/conda-forge/cython-blis-feedstock/issues/2

Ping @conda-forge/cython-blis team and @isuruf.

### CODE REVIEW

**Comment by echistyakov** [comment]
Package has a `broken` label: https://anaconda.org/conda-forge/cython-blis/files
Is it due to the failed build?

I ran into an issue when installing `spacy`:
```
ResolvePackageNotFound:
  - spacy==2.1.4 -> cython-blis[version='>=0.2.2,<0.3.0']
```

**Comment by ocefpaf** [comment]
> Package has a `broken` label: [anaconda.org/conda-forge/cython-blis/files](https://anaconda.org/conda-forge/cython-blis/files)
> Is it due to the failed build?

Nope. It is b/c of the missing license. See #2.

I don't know what is going on Windows here. I'm not a maintainer of this feedstock, just trying to solve the license problem.

**Comment by ocefpaf** [comment]
The failure now is to be due to a timeout when downloading the packages.
It seems that anaconda.org is down.

**Comment by buhrmann** [comment]
Same problem here. Seems that the package has been built now and is available here: https://anaconda.org/conda-forge/cython-blis/files right? 

However, `conda search cython-blis --channel conda-forge` still fails to find anything.

Do you know if that's some sort of caching issue on their side?

**Comment by isuruf** [comment]
CDN is updated every half an hour or so

**Comment by buhrmann** [comment]
Ok, makes sense, thanks!

**Pull request merged**
