### PR TITLE
fix migrator

### PR DESCRIPTION
**Pull request by jayfurmanek**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #14

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
Ready for review/merge. Note I removed the pin on wheel. I'm not sure why that was there.

**Comment by jayfurmanek** [comment]
There is still the pin for numpy in this recipe...
@isuruf I know we'd rather rely on the smithy scripts to define pins, but numpy is kind of special. Any recommendation here?

**Comment by jayfurmanek** [comment]
@honnibal @ines Can this one get a review? Thanks!

**Comment by jayfurmanek** [comment]
@xhochy Thoughts on this one?

**Comment by xhochy** [comment]
> @xhochy Thoughts on this one?

Not sure how I came to that mention but the PR looks good, so merging.

**Comment by jayfurmanek** [comment]
Thanks @xhochy !
I know you have nothing to do with maintaining this package, but I've been unable to raise the attention of the current maintainers. Thanks for merging!

**Pull request merged**
